name: snake_buddy
description: A snake classification application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  camera: ^0.10.5+2
  flutter:
    sdk: flutter
  image: ^4.0.17
  path: ^1.8.3
  path_provider: ^2.0.15
  image_picker: ^0.8.8
  wakelock_plus: ^1.2.8
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  flutter_inappwebview: ^6.1.5
  tflite_flutter: ^0.11.0
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/


  fonts:
    - family: Actor
      fonts:
      - asset: assets/fonts/Actor-Regular.ttf
